### ISSUE TITLE
Running pipeline with Uniprot ids which don't return orthologs

### ISSUE THREAD

**Issue by charlie-pugh** [nf-core/reportho#64]
Hi thank you for the lovely pipeline. Here I'm describing an issue I've had with my use case of running with many unirprot ids some of which may not be of the intended sort for these databases. 

### Description of the bug

I have been running the pipeline with a list of uniprot ids from diverse species and even viral proteins. In many cases these do not return hits from the databases, and these edge cases cause issues in some of the processes. 

I ran into 2 similar errors running the pipeline with and without orthofinder as described below, and I've attached the ids I used. 

### Command used and terminal output

-------------------------
#### Error 1 with input uniprot_ids.csv, with default settings
-------------------------
```
Caused by:
  Process `NFCORE_REPORTHO:REPORTHO:GET_ORTHOLOGS:FETCH_INSPECTOR_GROUP_ONLINE (OXDA_RHOTO)` terminated with an error exit status (1)

INFO:    Environment variable SINGULARITYENV_TMPDIR is set, but APPTAINERENV_TMPDIR is preferred
  INFO:    Environment variable SINGULARITYENV_NXF_TASK_WORKDIR is set, but APPTAINERENV_NXF_TASK_WORKDIR is preferred
  INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred
  Traceback (most recent call last):
    File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 971, in json
      return complexjson.loads(self.text, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
      return _default_decoder.decode(s)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
      obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
      raise JSONDecodeError("Expecting value", s, err.value) from None
  json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/users/diasfrazer/cpugh/.nextflow/assets/nf-core/reportho/bin/fetch_inspector_group.py", line 39, in <module>
      main()
    File "/users/diasfrazer/cpugh/.nextflow/assets/nf-core/reportho/bin/fetch_inspector_group.py", line 35, in main
      fetch_inspector_by_id(sys.argv[1], sys.argv[2])
    File "/users/diasfrazer/cpugh/.nextflow/assets/nf-core/reportho/bin/fetch_inspector_group.py", line 21, in fetch_inspector_by_id
      json = res.json()
             ^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 975, in json
      raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
  requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

-------------------------
#### Error 2, the same as for producing error 1, but setting skip_orthofinder to true in config. 
-------------------------
```
Caused by:
  Process `NFCORE_REPORTHO:REPORTHO:ALIGN:TCOFFEE_ALIGN (AMIE_PSEAE)` terminated with an error exit status (1)


Command executed:

  export TEMP='./'
  t_coffee -seq AMIE_PSEAE_orthologs.fa                                    -thread 6         -outfile stdout         > AMIE_PSEAE.aln
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_REPORTHO:REPORTHO:ALIGN:TCOFFEE_ALIGN":
      tcoffee: $( t_coffee -version | awk '{gsub("Version_", ""); print $3}')
      pigz: $(echo $(pigz --version 2>&1) | sed 's/^.*pigz\w*//' ))
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  -split_score_thres	D	[0] 	0 
  -check_pdb_status	D	[0] 	0 
  -clean_seq_name	D	[0] 	0 
  -seq_to_keep   	S	[0] 
  -dpa_master_aln	S	[0] 
  -dpa_maxnseq   	D	[0] 	0 
  -dpa_min_score1	D	[0] 
  -dpa_min_score2	D	[0] 
  -dpa_keep_tmpfile	FL	[0] 	0
  -dpa_debug     	D	[0] 	0 
  -multi_core    	S	[0] 	templates_jobs_relax_msa_evaluate
  -n_core        	D	[0] 	1 
  -thread        	D	[1] 	6 
  -max_n_proc    	D	[0] 	1 
  -lib_list      	S	[0] 
  -prune_lib_mode	S	[0] 	5
  -tip           	S	[0] 	none
  -rna_lib       	S	[0] 
  -no_warning    	D	[0] 	0 
  -run_local_script	D	[0] 	0 
  -proxy         	S	[0] 	unset
  -email         	S	[0] 
  -clean_overaln 	D	[0] 	0 
  -overaln_param 	S	[0] 
  -overaln_mode  	S	[0] 
  -overaln_model 	S	[0] 
  -overaln_threshold	D	[0] 	0 
  -overaln_target	D	[0] 	0 
  -overaln_P1    	D	[0] 	0 
  -overaln_P2    	D	[0] 	0 
  -overaln_P3    	D	[0] 	0 
  -overaln_P4    	D	[0] 	0 
  -exon_boundaries	S	[0] 
  -display       	D	[0] 	100 
  
  INPUT FILES
  	Input File (S) AMIE_PSEAE_orthologs.fa  Format 
  
  --ERROR: The format of AMIE_PSEAE_orthologs.fa is not supported
  
  
  *************************************************************************************************
  *                        FULL TRACE BACK PID: 42                                    
  42 -- ERROR: The format of AMIE_PSEAE_orthologs.fa is not supported
  42 -- COM: /usr/local/libexec/t-coffee-13.46.0.919e8c6b-0/bin/linux/t_coffee -seq AMIE_PSEAE_orthologs.fa -thread 6 -outfile stdout 
  42 -- STACK: 35 -> 42
  *************************************************************************************************
  
  # TERMINATION STATUS: FAILURE [PROGRAM: T-COFFEE pid 42 ppid 35
  #CL: /usr/local/libexec/t-coffee-13.46.0.919e8c6b-0/bin/linux/t_coffee -seq AMIE_PSEAE_orthologs.fa -thread 6 -outfile stdout 
 ```

### Relevant files

[uniprot_ids.csv.zip](https://github.com/user-attachments/files/17435621/uniprot_ids.csv.zip)

**Comment by itrujnara** [comment]
Presumed resolved, could not reproduce on the dev version. @charlie-pugh, please reopen if the issue is still present.
